services:
  app:
    build: .
    container_name: testPHP
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: testPHP-DB
    restart: always
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: rootPasSw0rd
      MYSQL_USER: test
      MYSQL_PASSWORD: PasSw0rd
    ports:
      - "3306:3306"
